# Generated by Django 6.1.1 on 2026-09-14 14:11

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_contract', models.CharField(choices=[('sales_v1', 'Original sales-file intake v1')], default='sales_v1', editable=False, max_length=32)),
                ('source_system', models.CharField(help_text='Stable name of the system that produced this file.', max_length=64)),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)')], editable=False, max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('storage_bucket', models.CharField(editable=False, max_length=63)),
                ('storage_key', models.CharField(editable=False, max_length=1024, unique=True)),
                ('storage_version_id', models.CharField(blank=True, editable=False, max_length=1024)),
                ('status', models.CharField(choices=[('receiving', 'Receiving'), ('received', 'Received'), ('failed', 'Storage failed')], db_index=True, default='receiving', editable=False, max_length=16)),
                ('failure_code', models.CharField(blank=True, choices=[('', 'None'), ('storage_error', 'Storage error')], default='', editable=False, max_length=32)),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source_system', '-created_at'], name='salesimp_source_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='sales_import_size_positive'), models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='sales_import_sha256_valid'), models.CheckConstraint(condition=models.Q(('source_system', django.db.models.functions.text.Upper('source_system'))), name='sales_import_source_uppercase'), models.CheckConstraint(condition=models.Q(('file_format__in', ('csv', 'xlsx'))), name='sales_import_format_valid'), models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', True), ('failure_code', ''), ('received_at__isnull', True), ('status', 'receiving'), ('storage_version_id', '')), models.Q(('failed_at__isnull', True), ('failure_code', ''), ('received_at__isnull', False), ('status', 'received'), models.Q(('storage_version_id', ''), _negated=True)), models.Q(('failed_at__isnull', False), ('received_at__isnull', True), ('status', 'failed'), ('storage_version_id', ''), models.Q(('failure_code', ''), _negated=True)), _connector='OR'), name='sales_import_status_metadata_consistent'), models.UniqueConstraint(models.F('data_contract'), models.F('source_system'), models.F('sha256'), condition=models.Q(('status__in', ('receiving', 'received'))), name='sales_import_active_file_unique')],
            },
        ),
    ]
