# Generated by Django 6.1.1 on 2026-09-15 11:12

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


def backfill_processing_jobs(apps, schema_editor):
    SalesImport = apps.get_model("sales_imports", "SalesImport")
    SalesImportJob = apps.get_model("sales_imports", "SalesImportJob")
    using = schema_editor.connection.alias

    jobs = []
    for sales_import in (
        SalesImport.objects.using(using).all().iterator(chunk_size=1000)
    ):
        status = "waiting_file"
        finished_at = None
        last_error_code = ""
        last_error_message = ""

        if sales_import.status == "received":
            status = "queued" if sales_import.file_format == "csv" else "awaiting_parser"
        elif sales_import.status == "failed":
            status = "failed"
            finished_at = sales_import.failed_at or django.utils.timezone.now()
            last_error_code = "INTAKE_STORAGE_FAILED"
            last_error_message = "The original file did not complete secure storage."

        jobs.append(
            SalesImportJob(
                sales_import_id=sales_import.pk,
                status=status,
                available_at=django.utils.timezone.now(),
                finished_at=finished_at,
                last_error_code=last_error_code,
                last_error_message=last_error_message,
            )
        )
        if len(jobs) == 1000:
            SalesImportJob.objects.using(using).bulk_create(jobs, batch_size=1000)
            jobs.clear()

    if jobs:
        SalesImportJob.objects.using(using).bulk_create(jobs, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0004_calendar_timezone_and_source_whitespace'),
        ('master_data', '0007_immutable_territory_level'),
        ('sales_imports', '0003_sales_row_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImportJob',
            fields=[
                ('sales_import', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='processing_job', serialize=False, to='sales_imports.salesimport')),
                ('status', models.CharField(choices=[('waiting_file', 'Waiting for file'), ('awaiting_parser', 'Awaiting format parser'), ('queued', 'Queued'), ('processing', 'Processing'), ('retry_wait', 'Waiting to retry'), ('published', 'Published'), ('rejected', 'Rejected'), ('failed', 'Processing failed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting_file', editable=False, max_length=16)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('attempt_count', models.PositiveIntegerField(default=0, editable=False)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, editable=False)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('leased_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('lease_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('total_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('valid_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('invalid_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('issue_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('inserted_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('reused_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('last_error_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('last_error_message', models.CharField(blank=True, editable=False, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(condition=models.Q(('status__in', ('queued', 'retry_wait'))), fields=['status', 'available_at', 'created_at'], name='sales_job_claim_idx'), models.Index(condition=models.Q(('status', 'processing')), fields=['lease_expires_at'], name='sales_job_expired_lease_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('waiting_file', 'awaiting_parser', 'queued', 'processing', 'retry_wait', 'published', 'rejected', 'failed', 'cancelled'))), name='sales_job_status_valid'), models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0), ('attempt_count__lte', models.F('max_attempts'))), name='sales_job_attempts_valid'), models.CheckConstraint(condition=models.Q(('total_rows', django.db.models.expressions.CombinedExpression(models.F('valid_rows'), '+', models.F('invalid_rows'))), ('issue_count__gte', models.F('invalid_rows'))), name='sales_job_counts_valid'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('first_started_at__isnull', False), ('heartbeat_at__isnull', False), ('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('status', 'processing'), models.Q(('leased_by', ''), _negated=True)), models.Q(models.Q(('status', 'processing'), _negated=True), ('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('lease_token__isnull', True), ('leased_by', '')), _connector='OR'), name='sales_job_lease_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ('published', 'rejected', 'failed', 'cancelled'))), models.Q(('finished_at__isnull', True), ('status__in', ('waiting_file', 'awaiting_parser', 'queued', 'processing', 'retry_wait'))), _connector='OR'), name='sales_job_finished_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('invalid_rows', 0), ('issue_count', 0), ('status', 'published'), ('total_rows', models.F('valid_rows')), ('valid_rows', django.db.models.expressions.CombinedExpression(models.F('inserted_rows'), '+', models.F('reused_rows')))), models.Q(models.Q(('status', 'published'), _negated=True), ('inserted_rows', 0), ('reused_rows', 0)), _connector='OR'), name='sales_job_publish_counts_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('issue_count__gt', 0), ('status', 'rejected')), _connector='OR'), name='sales_job_rejection_has_issue'), models.CheckConstraint(condition=models.Q(('leased_by', django.db.models.functions.text.Trim('leased_by'))), name='sales_job_worker_trimmed')],
            },
        ),
        migrations.CreateModel(
            name='SalesImportAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(editable=False)),
                ('lease_token', models.UUIDField(editable=False)),
                ('worker_id', models.CharField(editable=False, max_length=255)),
                ('phase', models.CharField(choices=[('claimed', 'Claimed'), ('download', 'Download'), ('parse', 'Parse'), ('validate', 'Validate'), ('publish', 'Publish'), ('complete', 'Complete')], default='claimed', editable=False, max_length=16)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('published', 'Published'), ('rejected', 'Rejected'), ('retryable_failure', 'Retryable failure'), ('permanent_failure', 'Permanent failure'), ('lease_expired', 'Lease expired'), ('cancelled', 'Cancelled')], db_index=True, default='running', editable=False, max_length=24)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('total_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('valid_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('invalid_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('issue_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('inserted_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('reused_rows', models.PositiveBigIntegerField(default=0, editable=False)),
                ('error_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('error_message', models.CharField(blank=True, editable=False, max_length=1000)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='sales_imports.salesimportjob')),
            ],
            options={
                'ordering': ('job_id', '-attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='SalesImportStagedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveBigIntegerField(editable=False)),
                ('source_record_id', models.CharField(editable=False, max_length=255)),
                ('transaction_date', models.DateField(editable=False)),
                ('product_code', models.CharField(editable=False, max_length=64)),
                ('territory_code', models.CharField(editable=False, max_length=64)),
                ('hospital_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('sales_representative_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=3, editable=False, max_digits=18)),
                ('revenue_amount', models.DecimalField(decimal_places=4, editable=False, max_digits=20)),
                ('currency_code', models.CharField(editable=False, max_length=3)),
                ('outcome', models.CharField(choices=[('staged', 'Staged'), ('published', 'Published'), ('reused', 'Reused existing fact')], default='staged', editable=False, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='staged_rows', to='sales_imports.salesimportattempt')),
                ('calendar_date', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_import_rows', to='business_data.calendardate')),
                ('hospital', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_import_rows', to='master_data.hospital')),
                ('product', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_import_rows', to='master_data.product')),
                ('sales_representative', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_import_rows', to='master_data.salesrepresentative')),
                ('sales_transaction', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_import_rows', to='business_data.salestransaction')),
                ('territory', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_import_rows', to='master_data.territory')),
            ],
            options={
                'ordering': ('attempt_id', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='SalesImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('column', models.CharField(editable=False, max_length=64)),
                ('code', models.CharField(editable=False, max_length=64)),
                ('message', models.CharField(editable=False, max_length=1000)),
                ('phase', models.CharField(choices=[('contract', 'File contract'), ('master_data', 'Master data'), ('idempotency', 'Idempotency')], editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='sales_imports.salesimportattempt')),
            ],
            options={
                'ordering': ('attempt_id', 'row_number', 'id'),
                'indexes': [models.Index(fields=['attempt', 'row_number', 'id'], name='sales_issue_row_idx'), models.Index(fields=['attempt', 'code'], name='sales_issue_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'row_number', 'column', 'code'), name='sales_issue_identity_unique', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('row_number__isnull', True), ('row_number__gte', 2), _connector='OR'), name='sales_issue_row_number_valid'), models.CheckConstraint(condition=models.Q(('phase__in', ('contract', 'master_data', 'idempotency'))), name='sales_issue_phase_valid'), models.CheckConstraint(condition=models.Q(('column', django.db.models.functions.text.Trim('column')), models.Q(('column', ''), _negated=True), ('code__regex', '^[A-Z][A-Z0-9_]*$'), ('message', django.db.models.functions.text.Trim('message')), models.Q(('message', ''), _negated=True)), name='sales_issue_text_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='salesimportattempt',
            index=models.Index(fields=['job', '-attempt_number'], name='sales_attempt_job_number_idx'),
        ),
        migrations.AddIndex(
            model_name='salesimportattempt',
            index=models.Index(fields=['outcome', 'started_at'], name='sales_attempt_outcome_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt_number'), name='sales_attempt_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'running')), fields=('job',), name='sales_attempt_one_running'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='sales_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(('worker_id', django.db.models.functions.text.Trim('worker_id')), models.Q(('worker_id', ''), _negated=True)), name='sales_attempt_worker_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(('phase__in', ('claimed', 'download', 'parse', 'validate', 'publish', 'complete'))), name='sales_attempt_phase_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ('running', 'published', 'rejected', 'retryable_failure', 'permanent_failure', 'lease_expired', 'cancelled'))), name='sales_attempt_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('outcome', 'running')), models.Q(models.Q(('outcome', 'running'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='sales_attempt_finished_consistent'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(('total_rows', django.db.models.expressions.CombinedExpression(models.F('valid_rows'), '+', models.F('invalid_rows'))), ('issue_count__gte', models.F('invalid_rows'))), name='sales_attempt_counts_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invalid_rows', 0), ('issue_count', 0), ('outcome', 'published'), ('total_rows', models.F('valid_rows')), ('valid_rows', django.db.models.expressions.CombinedExpression(models.F('inserted_rows'), '+', models.F('reused_rows')))), models.Q(models.Q(('outcome', 'published'), _negated=True), ('inserted_rows', 0), ('reused_rows', 0)), _connector='OR'), name='sales_attempt_publish_counts_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'rejected'), _negated=True), models.Q(('issue_count__gt', 0), ('outcome', 'rejected')), _connector='OR'), name='sales_attempt_rejection_has_issue'),
        ),
        migrations.AddIndex(
            model_name='salesimportstagedrow',
            index=models.Index(fields=['attempt', 'source_record_id'], name='sales_staged_source_idx'),
        ),
        migrations.AddIndex(
            model_name='salesimportstagedrow',
            index=models.Index(fields=['attempt', 'transaction_date'], name='sales_staged_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.UniqueConstraint(fields=('attempt', 'row_number'), name='sales_staged_row_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.UniqueConstraint(fields=('attempt', 'source_record_id'), name='sales_staged_source_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 2)), name='sales_staged_row_number_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('source_record_id', django.db.models.functions.text.Trim('source_record_id')), models.Q(('source_record_id', ''), _negated=True)), name='sales_staged_source_id_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('product_code', django.db.models.functions.text.Upper('product_code')), ('product_code', django.db.models.functions.text.Trim('product_code')), models.Q(('product_code', ''), _negated=True), ('territory_code', django.db.models.functions.text.Upper('territory_code')), ('territory_code', django.db.models.functions.text.Trim('territory_code')), models.Q(('territory_code', ''), _negated=True)), name='sales_staged_required_codes_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('hospital_code', django.db.models.functions.text.Upper('hospital_code')), ('hospital_code', django.db.models.functions.text.Trim('hospital_code')), ('sales_representative_code', django.db.models.functions.text.Upper('sales_representative_code')), ('sales_representative_code', django.db.models.functions.text.Trim('sales_representative_code'))), name='sales_staged_optional_codes_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('currency_code__regex', '^[A-Z]{3}$')), name='sales_staged_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity', 0), _negated=True), models.Q(models.Q(('quantity__gt', Decimal('0')), ('revenue_amount__gte', 0)), models.Q(('quantity__lt', Decimal('0')), ('revenue_amount__lte', 0)), _connector='OR')), name='sales_staged_measures_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ('staged', 'published', 'reused'))), name='sales_staged_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimportstagedrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'staged'), ('sales_transaction__isnull', True)), models.Q(('calendar_date__isnull', False), ('outcome__in', ('published', 'reused')), ('product__isnull', False), ('sales_transaction__isnull', False), ('territory__isnull', False), models.Q(models.Q(('hospital__isnull', True), ('hospital_code', '')), models.Q(models.Q(('hospital_code', ''), _negated=True), ('hospital__isnull', False)), _connector='OR'), models.Q(models.Q(('sales_representative__isnull', True), ('sales_representative_code', '')), models.Q(models.Q(('sales_representative_code', ''), _negated=True), ('sales_representative__isnull', False)), _connector='OR')), _connector='OR'), name='sales_staged_result_consistent'),
        ),
        migrations.RunPython(
            backfill_processing_jobs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
