# Generated by Django 6.1.1 on 2026-09-15 11:56

import django.db.models.functions.text
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def prevent_unsafe_reverse(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM sales_imports_salesimport LIMIT 1")
        has_imports = cursor.fetchone() is not None
    if has_imports:
        raise IrreversibleError(
            "KMS provenance cannot be removed after sales-import audit records "
            "exist."
        )


FORWARD_SQL = """
CREATE OR REPLACE FUNCTION sales_imports_protect_audit_row()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales import audit records cannot be deleted.',
            CONSTRAINT = 'sales_import_audit_immutable';
    END IF;

    IF NOT (
        (OLD.status = 'receiving' AND NEW.status IN ('received', 'failed'))
        OR (OLD.status = 'received' AND NEW.status = 'failed')
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'The sales import status transition is not allowed.',
            CONSTRAINT = 'sales_import_status_transition_valid';
    END IF;

    IF ROW(
        NEW.id,
        NEW.data_contract,
        NEW.row_contract,
        NEW.source_system,
        NEW.original_filename,
        NEW.content_type,
        NEW.file_format,
        NEW.size_bytes,
        NEW.sha256,
        NEW.storage_bucket,
        NEW.storage_kms_key_arn,
        NEW.storage_key,
        NEW.uploaded_by_id,
        NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.id,
        OLD.data_contract,
        OLD.row_contract,
        OLD.source_system,
        OLD.original_filename,
        OLD.content_type,
        OLD.file_format,
        OLD.size_bytes,
        OLD.sha256,
        OLD.storage_bucket,
        OLD.storage_kms_key_arn,
        OLD.storage_key,
        OLD.uploaded_by_id,
        OLD.created_at
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales import lineage fields are immutable.',
            CONSTRAINT = 'sales_import_lineage_immutable';
    END IF;

    RETURN NEW;
END;
$$;
"""


REVERSE_SQL = """
CREATE OR REPLACE FUNCTION sales_imports_protect_audit_row()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales import audit records cannot be deleted.',
            CONSTRAINT = 'sales_import_audit_immutable';
    END IF;

    IF OLD.status <> 'receiving'
       OR NEW.status = OLD.status
       OR NEW.status NOT IN ('received', 'failed')
    THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'The sales import status transition is not allowed.',
            CONSTRAINT = 'sales_import_status_transition_valid';
    END IF;

    IF ROW(
        NEW.id,
        NEW.data_contract,
        NEW.row_contract,
        NEW.source_system,
        NEW.original_filename,
        NEW.content_type,
        NEW.file_format,
        NEW.size_bytes,
        NEW.sha256,
        NEW.storage_bucket,
        NEW.storage_key,
        NEW.uploaded_by_id,
        NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.id,
        OLD.data_contract,
        OLD.row_contract,
        OLD.source_system,
        OLD.original_filename,
        OLD.content_type,
        OLD.file_format,
        OLD.size_bytes,
        OLD.sha256,
        OLD.storage_bucket,
        OLD.storage_key,
        OLD.uploaded_by_id,
        OLD.created_at
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales import lineage fields are immutable.',
            CONSTRAINT = 'sales_import_lineage_immutable';
    END IF;

    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('sales_imports', '0004_processing_persistence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesimport',
            name='sales_import_status_metadata_consistent',
        ),
        migrations.AddField(
            model_name='salesimport',
            name='storage_kms_key_arn',
            field=models.CharField(blank=True, editable=False, help_text='Exact KMS key ARN recorded when the original object was stored; null only for imports created before key provenance was introduced.', max_length=2048, null=True),
        ),
        migrations.AddConstraint(
            model_name='salesimport',
            constraint=models.CheckConstraint(condition=models.Q(('storage_kms_key_arn__isnull', True), models.Q(('storage_kms_key_arn', django.db.models.functions.text.Trim('storage_kms_key_arn')), ('storage_kms_key_arn__regex', '^arn:[^:]+:kms:[^:]+:[0-9]{12}:key/.+$')), _connector='OR'), name='sales_import_kms_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesimport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', True), ('failure_code', ''), ('received_at__isnull', True), ('status', 'receiving'), ('storage_version_id', '')), models.Q(('failed_at__isnull', True), ('failure_code', ''), ('received_at__isnull', False), ('status', 'received'), models.Q(('storage_version_id', ''), _negated=True)), models.Q(('failed_at__isnull', False), ('status', 'failed'), models.Q(('failure_code', ''), _negated=True), models.Q(models.Q(('received_at__isnull', True), ('storage_version_id', '')), models.Q(('received_at__isnull', False), models.Q(('storage_version_id', ''), _negated=True)), _connector='OR')), _connector='OR'), name='sales_import_status_metadata_consistent'),
        ),
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=prevent_unsafe_reverse,
        ),
    ]
