# Generated by Django 6.1.1 on 2026-09-13 17:41

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0007_immutable_territory_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('date_key', models.PositiveIntegerField(editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('quarter', models.PositiveSmallIntegerField(editable=False)),
                ('month', models.PositiveSmallIntegerField(editable=False)),
                ('month_name', models.CharField(editable=False, max_length=9)),
                ('month_abbreviation', models.CharField(editable=False, max_length=3)),
                ('day_of_month', models.PositiveSmallIntegerField(editable=False)),
                ('day_of_year', models.PositiveSmallIntegerField(editable=False)),
                ('iso_year', models.PositiveSmallIntegerField(editable=False)),
                ('iso_week', models.PositiveSmallIntegerField(editable=False)),
                ('iso_weekday', models.PositiveSmallIntegerField(editable=False)),
                ('weekday_name', models.CharField(editable=False, max_length=9)),
                ('is_weekend', models.BooleanField(editable=False)),
                ('week_start', models.DateField(editable=False)),
                ('week_end', models.DateField(editable=False)),
                ('month_start', models.DateField(editable=False)),
                ('month_end', models.DateField(editable=False)),
                ('quarter_start', models.DateField(editable=False)),
                ('quarter_end', models.DateField(editable=False)),
                ('year_start', models.DateField(editable=False)),
                ('year_end', models.DateField(editable=False)),
                ('year_month_key', models.PositiveIntegerField(editable=False)),
                ('year_month_label', models.CharField(editable=False, max_length=8)),
                ('year_quarter_label', models.CharField(editable=False, max_length=7)),
            ],
            options={
                'verbose_name': 'calendar date',
                'ordering': ('date',),
                'indexes': [models.Index(fields=['year', 'month'], name='bd_calendar_month_idx'), models.Index(fields=['iso_year', 'iso_week'], name='bd_calendar_iso_week_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('year', django.db.models.functions.datetime.ExtractYear('date'))), name='business_data_calendar_year_matches'), models.CheckConstraint(condition=models.Q(('quarter', django.db.models.functions.datetime.ExtractQuarter('date'))), name='business_data_calendar_quarter_matches'), models.CheckConstraint(condition=models.Q(('month', django.db.models.functions.datetime.ExtractMonth('date'))), name='business_data_calendar_month_matches'), models.CheckConstraint(condition=models.Q(('day_of_month', django.db.models.functions.datetime.ExtractDay('date'))), name='business_data_calendar_day_matches'), models.CheckConstraint(condition=models.Q(('iso_year', django.db.models.functions.datetime.ExtractIsoYear('date'))), name='business_data_calendar_iso_year_matches'), models.CheckConstraint(condition=models.Q(('iso_week', django.db.models.functions.datetime.ExtractWeek('date'))), name='business_data_calendar_iso_week_matches'), models.CheckConstraint(condition=models.Q(('iso_weekday', django.db.models.functions.datetime.ExtractIsoWeekDay('date'))), name='business_data_calendar_iso_day_matches'), models.CheckConstraint(condition=models.Q(('date_key', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('year'), '*', models.Value(10000)), '+', django.db.models.expressions.CombinedExpression(models.F('month'), '*', models.Value(100))), '+', models.F('day_of_month')))), name='business_data_calendar_date_key_matches'), models.CheckConstraint(condition=models.Q(('year_month_key', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('year'), '*', models.Value(100)), '+', models.F('month')))), name='business_data_calendar_month_key_matches'), models.CheckConstraint(condition=models.Q(('week_start__lte', models.F('date')), ('week_end__gte', models.F('date')), ('week_end', django.db.models.expressions.CombinedExpression(models.F('week_start'), '+', models.Value(datetime.timedelta(days=6))))), name='business_data_calendar_week_bounds'), models.CheckConstraint(condition=models.Q(('month_start__lte', models.F('date')), ('month_end__gte', models.F('date'))), name='business_data_calendar_month_bounds'), models.CheckConstraint(condition=models.Q(('quarter_start__lte', models.F('date')), ('quarter_end__gte', models.F('date'))), name='business_data_calendar_quarter_bounds'), models.CheckConstraint(condition=models.Q(('year_start__lte', models.F('date')), ('year_end__gte', models.F('date'))), name='business_data_calendar_year_bounds'), models.CheckConstraint(condition=models.Q(models.Q(('is_weekend', True), ('iso_weekday__in', (6, 7))), models.Q(('is_weekend', False), ('iso_weekday__range', (1, 5))), _connector='OR'), name='business_data_calendar_weekend_matches')],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive for a sale and negative for a return; zero is invalid.', max_digits=18)),
                ('revenue_amount', models.DecimalField(decimal_places=4, help_text='Non-negative for a sale and non-positive for a return.', max_digits=20)),
                ('currency_code', models.CharField(help_text='Three-letter uppercase currency code, such as INR or USD.', max_length=3)),
                ('source_system', models.CharField(help_text='Stable name of the source system or file contract.', max_length=64)),
                ('source_record_id', models.CharField(help_text='Stable identifier for this exact line inside its source.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_date', models.ForeignKey(help_text='Business date on which this source line occurred.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='business_data.calendardate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_transactions', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, db_index=False, help_text='Leave empty only when the source line did not provide a hospital.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='master_data.hospital')),
                ('product', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='master_data.product')),
                ('sales_representative', models.ForeignKey(blank=True, db_index=False, help_text='Leave empty only when the source line did not provide a representative.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='master_data.salesrepresentative')),
                ('territory', models.ForeignKey(db_index=False, help_text='Leaf Territory explicitly attributed by the source.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='master_data.territory')),
            ],
            options={
                'ordering': ('-calendar_date', '-id'),
                'indexes': [models.Index(fields=['product', 'calendar_date'], name='bd_sales_product_date_idx'), models.Index(fields=['territory', 'calendar_date'], name='bd_sales_territory_date_idx'), models.Index(condition=models.Q(('hospital__isnull', False)), fields=['hospital', 'calendar_date'], name='bd_sales_hospital_date_idx'), models.Index(condition=models.Q(('sales_representative__isnull', False)), fields=['sales_representative', 'calendar_date'], name='bd_sales_rep_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_record_id'), name='business_data_sales_source_unique', violation_error_message='That source system and source record ID already exist.'), models.CheckConstraint(condition=models.Q(('source_system__regex', '^\\s*$'), _negated=True), name='business_data_sales_source_not_blank'), models.CheckConstraint(condition=models.Q(('source_system', django.db.models.functions.text.Trim('source_system'))), name='business_data_sales_source_trimmed'), models.CheckConstraint(condition=models.Q(('source_system', django.db.models.functions.text.Upper('source_system'))), name='business_data_sales_source_uppercase'), models.CheckConstraint(condition=models.Q(('source_record_id__regex', '^\\s*$'), _negated=True), name='business_data_sales_record_id_not_blank'), models.CheckConstraint(condition=models.Q(('source_record_id', django.db.models.functions.text.Trim('source_record_id'))), name='business_data_sales_record_id_trimmed'), models.CheckConstraint(condition=models.Q(('currency_code__regex', '^[A-Z]{3}$')), name='business_data_sales_currency_format'), models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='business_data_sales_quantity_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('quantity__gt', 0), ('revenue_amount__gte', 0)), models.Q(('quantity__lt', 0), ('revenue_amount__lte', 0)), _connector='OR'), name='business_data_sales_measure_signs')],
            },
        ),
    ]
