# Generated by Django 6.1.1 on 2026-09-13 18:20

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


FORWARD_SQL = """
CREATE OR REPLACE FUNCTION business_data_validate_sales_leaf_territory()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    assigned_level text;
BEGIN
    SELECT level INTO assigned_level
    FROM master_data_territory
    WHERE id = NEW.territory_id;

    IF assigned_level IS DISTINCT FROM 'territory' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales transactions require a Territory-level geography.',
            CONSTRAINT = 'business_data_sales_requires_leaf_territory';
    END IF;

    RETURN NEW;
END;
$$;

CREATE FUNCTION business_data_derive_calendar_date()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    calendar_year integer;
    calendar_quarter integer;
    calendar_month integer;
    calendar_day integer;
    iso_day integer;
BEGIN
    calendar_year := EXTRACT(YEAR FROM NEW.date)::integer;
    calendar_quarter := EXTRACT(QUARTER FROM NEW.date)::integer;
    calendar_month := EXTRACT(MONTH FROM NEW.date)::integer;
    calendar_day := EXTRACT(DAY FROM NEW.date)::integer;
    iso_day := EXTRACT(ISODOW FROM NEW.date)::integer;

    NEW.date_key := calendar_year * 10000 + calendar_month * 100 + calendar_day;
    NEW.year := calendar_year;
    NEW.quarter := calendar_quarter;
    NEW.month := calendar_month;
    NEW.month_name := CASE calendar_month
        WHEN 1 THEN 'January' WHEN 2 THEN 'February' WHEN 3 THEN 'March'
        WHEN 4 THEN 'April' WHEN 5 THEN 'May' WHEN 6 THEN 'June'
        WHEN 7 THEN 'July' WHEN 8 THEN 'August' WHEN 9 THEN 'September'
        WHEN 10 THEN 'October' WHEN 11 THEN 'November' WHEN 12 THEN 'December'
    END;
    NEW.month_abbreviation := CASE calendar_month
        WHEN 1 THEN 'Jan' WHEN 2 THEN 'Feb' WHEN 3 THEN 'Mar'
        WHEN 4 THEN 'Apr' WHEN 5 THEN 'May' WHEN 6 THEN 'Jun'
        WHEN 7 THEN 'Jul' WHEN 8 THEN 'Aug' WHEN 9 THEN 'Sep'
        WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dec'
    END;
    NEW.day_of_month := calendar_day;
    NEW.day_of_year := EXTRACT(DOY FROM NEW.date)::integer;
    NEW.iso_year := EXTRACT(ISOYEAR FROM NEW.date)::integer;
    NEW.iso_week := EXTRACT(WEEK FROM NEW.date)::integer;
    NEW.iso_weekday := iso_day;
    NEW.weekday_name := CASE iso_day
        WHEN 1 THEN 'Monday' WHEN 2 THEN 'Tuesday' WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday' WHEN 5 THEN 'Friday' WHEN 6 THEN 'Saturday'
        WHEN 7 THEN 'Sunday'
    END;
    NEW.is_weekend := iso_day IN (6, 7);
    NEW.week_start := NEW.date - (iso_day - 1);
    NEW.week_end := NEW.date + (7 - iso_day);
    NEW.month_start := date_trunc('month', NEW.date)::date;
    NEW.month_end := (
        date_trunc('month', NEW.date) + INTERVAL '1 month - 1 day'
    )::date;
    NEW.quarter_start := date_trunc('quarter', NEW.date)::date;
    NEW.quarter_end := (
        date_trunc('quarter', NEW.date) + INTERVAL '3 months - 1 day'
    )::date;
    NEW.year_start := date_trunc('year', NEW.date)::date;
    NEW.year_end := (
        date_trunc('year', NEW.date) + INTERVAL '1 year - 1 day'
    )::date;
    NEW.year_month_key := calendar_year * 100 + calendar_month;
    NEW.year_month_label := NEW.month_abbreviation || ' '
        || lpad(calendar_year::text, 4, '0');
    NEW.year_quarter_label := lpad(calendar_year::text, 4, '0')
        || ' Q' || calendar_quarter::text;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bd_calendar_derive_write_trigger
BEFORE INSERT OR UPDATE
ON business_data_calendardate
FOR EACH ROW
EXECUTE FUNCTION business_data_derive_calendar_date();

UPDATE business_data_calendardate SET date = date;

DROP TRIGGER bd_calendar_derive_write_trigger
ON business_data_calendardate;

CREATE TRIGGER bd_calendar_derive_insert_trigger
BEFORE INSERT
ON business_data_calendardate
FOR EACH ROW
EXECUTE FUNCTION business_data_derive_calendar_date();

CREATE FUNCTION business_data_prevent_calendar_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'Calendar dates are immutable.',
        CONSTRAINT = 'business_data_calendar_immutable';
END;
$$;

CREATE TRIGGER bd_calendar_immutable_trigger
BEFORE UPDATE OR DELETE
ON business_data_calendardate
FOR EACH ROW
EXECUTE FUNCTION business_data_prevent_calendar_mutation();
"""


REVERSE_SQL = """
DROP TRIGGER IF EXISTS bd_calendar_immutable_trigger
ON business_data_calendardate;
DROP FUNCTION IF EXISTS business_data_prevent_calendar_mutation();

DROP TRIGGER IF EXISTS bd_calendar_derive_insert_trigger
ON business_data_calendardate;
DROP FUNCTION IF EXISTS business_data_derive_calendar_date();

CREATE OR REPLACE FUNCTION business_data_validate_sales_leaf_territory()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    assigned_level text;
BEGIN
    SELECT level INTO assigned_level
    FROM master_data_territory
    WHERE id = NEW.territory_id;

    IF assigned_level IS NOT NULL AND assigned_level <> 'territory' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'Sales transactions require a Territory-level geography.',
            CONSTRAINT = 'business_data_sales_requires_leaf_territory';
    END IF;

    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0002_sales_transaction_guards'),
        ('master_data', '0007_immutable_territory_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendardate',
            constraint=models.CheckConstraint(condition=models.Q(('date__range', (datetime.date(1, 1, 1), datetime.date(9998, 12, 31)))), name='business_data_calendar_supported_date'),
        ),
        migrations.AlterModelOptions(
            name='salestransaction',
            options={},
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='calendar_date',
            field=models.ForeignKey(db_index=False, help_text='Business date on which this source line occurred.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='business_data.calendardate'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['-calendar_date', '-id'], name='bd_sales_date_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__regex', '^[[:space:]]|[[:space:]]$'), _negated=True), name='business_data_sales_source_no_edge_space'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_record_id__regex', '^[[:space:]]|[[:space:]]$'), _negated=True), name='business_data_sales_record_no_edge_space'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('-1000000000000000')), ('quantity__lt', Decimal('1000000000000000'))), name='business_data_sales_quantity_finite'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_amount__gt', Decimal('-10000000000000000')), ('revenue_amount__lt', Decimal('10000000000000000'))), name='business_data_sales_revenue_finite'),
        ),
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
