# Generated by Django 6.1.1 on 2026-09-11 20:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate products that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'code'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='master_data_product_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_product_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_product_name_not_blank')],
            },
        ),
    ]
