# Generated by Django 6.1.1 on 2026-09-11 21:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate records that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('zone', 'Zone'), ('region', 'Region'), ('area', 'Area'), ('territory', 'Territory')], db_index=True, default='territory', help_text='Commercial level represented by this record.', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'territories',
                'ordering': ('name', 'code'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='master_data_territory_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_territory_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_territory_name_not_blank'), models.CheckConstraint(condition=models.Q(('level__in', ('zone', 'region', 'area', 'territory'))), name='master_data_territory_level_valid')],
            },
        ),
    ]
