# Generated by Django 6.1.1 on 2026-09-11 21:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_territory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='master_data_product_code_case_insensitive_unique',
        ),
        migrations.RemoveConstraint(
            model_name='territory',
            name='master_data_territory_code_case_insensitive_unique',
        ),
        migrations.AlterField(
            model_name='territory',
            name='level',
            field=models.CharField(choices=[('zone', 'Zone'), ('region', 'Region'), ('area', 'Area'), ('territory', 'Territory')], db_index=True, help_text='Commercial level represented by this record.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_product_code_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_product_code_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_product_name_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_territory_code_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_territory_code_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_territory_name_trimmed'),
        ),
    ]
