# Generated by Django 6.1.1 on 2026-09-11 21:58

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_master_data_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate records that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'doctor / HCP',
                'verbose_name_plural': 'doctors / HCPs',
                'ordering': ('name', 'code'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_hcp_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_hcp_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_hcp_name_not_blank'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_hcp_code_trimmed'), models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_hcp_name_trimmed')],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate records that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'code'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_hospital_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_hospital_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_hospital_name_not_blank'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_hospital_code_trimmed'), models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_hospital_name_trimmed')],
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate records that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional application login belonging to this representative.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'code'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_sales_rep_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_sales_rep_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_sales_rep_name_not_blank'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_sales_rep_code_trimmed'), models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_sales_rep_name_trimmed')],
            },
        ),
    ]
