# Generated by Django 6.1.1 on 2026-09-13 16:31

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.text
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_healthcareprofessional_hospital_salesrepresentative'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable company code used in files and integrations.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate records that should no longer be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ('name', 'code'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='master_data_specialty_code_case_insensitive_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '^\\s*$'), _negated=True), name='master_data_specialty_code_not_blank'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='master_data_specialty_name_not_blank'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim('code'))), name='master_data_specialty_code_trimmed'), models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim('name'))), name='master_data_specialty_name_trimmed')],
            },
        ),
        migrations.CreateModel(
            name='HealthcareProfessionalHospitalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First date on which this assignment applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last date on which this assignment applies; leave blank if ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Mark the HCP's main hospital for this period.")),
                ('healthcare_professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_affiliations', to='master_data.healthcareprofessional')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hcp_affiliations', to='master_data.hospital')),
            ],
            options={
                'verbose_name': 'doctor / HCP hospital affiliation',
                'verbose_name_plural': 'doctor / HCP hospital affiliations',
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='master_data_hcp_hospital_dates_valid', violation_error_message='The effective end date must be on or after the start date.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('healthcare_professional', '='), ('hospital', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_hcp_hospital_no_overlap', violation_error_message='This HCP and hospital already overlap during that period.'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_primary', True)), expressions=[('healthcare_professional', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_hcp_hospital_one_primary', violation_error_message='This HCP already has a primary hospital during that period.')],
            },
        ),
        migrations.CreateModel(
            name='HospitalTerritoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First date on which this assignment applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last date on which this assignment applies; leave blank if ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territory_assignments', to='master_data.hospital')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_assignments', to='master_data.territory')),
            ],
            options={
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='master_data_hospital_territory_dates_valid', violation_error_message='The effective end date must be on or after the start date.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('hospital', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_hospital_territory_no_overlap', violation_error_message='This hospital already has a territory during part of that period.')],
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentativeTerritoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First date on which this assignment applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last date on which this assignment applies; leave blank if ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('support', 'Support')], help_text='Primary owner or supporting coverage for this territory.', max_length=7)),
                ('sales_representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territory_assignments', to='master_data.salesrepresentative')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative_assignments', to='master_data.territory')),
            ],
            options={
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='master_data_sales_rep_territory_dates_valid', violation_error_message='The effective end date must be on or after the start date.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('sales_representative', '='), ('territory', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_sales_rep_territory_no_overlap', violation_error_message='This representative and territory already overlap in that period.'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('assignment_type', 'primary')), expressions=[('territory', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_sales_rep_territory_one_primary', violation_error_message='This territory already has a primary representative then.'), models.CheckConstraint(condition=models.Q(('assignment_type__in', ('primary', 'support'))), name='master_data_sales_rep_assignment_type_valid', violation_error_message='Choose Primary or Support.')],
            },
        ),
        migrations.CreateModel(
            name='HealthcareProfessionalSpecialtyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First date on which this assignment applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last date on which this assignment applies; leave blank if ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Mark the HCP's main specialty for this period.")),
                ('healthcare_professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_assignments', to='master_data.healthcareprofessional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hcp_assignments', to='master_data.specialty')),
            ],
            options={
                'verbose_name': 'doctor / HCP specialty assignment',
                'verbose_name_plural': 'doctor / HCP specialty assignments',
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='master_data_hcp_specialty_dates_valid', violation_error_message='The effective end date must be on or after the start date.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('healthcare_professional', '='), ('specialty', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_hcp_specialty_no_overlap', violation_error_message='This HCP and specialty already overlap during that period.'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_primary', True)), expressions=[('healthcare_professional', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_hcp_specialty_one_primary', violation_error_message='This HCP already has a primary specialty during that period.')],
            },
        ),
        migrations.CreateModel(
            name='TerritoryHierarchyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First date on which this assignment applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last date on which this assignment applies; leave blank if ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_assignments', to='master_data.territory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_assignments', to='master_data.territory')),
            ],
            options={
                'verbose_name': 'territory hierarchy assignment',
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='master_data_territory_hierarchy_dates_valid', violation_error_message='The effective end date must be on or after the start date.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('child', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[]'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='master_data_territory_hierarchy_no_overlap', violation_error_message='This geography already has a parent during part of that period.'), models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='master_data_territory_hierarchy_not_self', violation_error_message='A geography cannot be its own parent.')],
            },
        ),
    ]
